version: '3.8'

services:
  db:
    build: .
    container_name: MYSQL
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Santino0503
      MYSQL_DATABASE: mydockerdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: